const EVENT_ROLES = {
  OWNER: 'owner',
  ADMIN: 'admin',
  STAFF: 'staff',
};

const EVENT_ROLE_OPTIONS = [EVENT_ROLES.OWNER, EVENT_ROLES.ADMIN, EVENT_ROLES.STAFF];
const MANAGEMENT_ROLES = [EVENT_ROLES.OWNER, EVENT_ROLES.ADMIN];

module.exports = {
  EVENT_ROLES,
  EVENT_ROLE_OPTIONS,
  MANAGEMENT_ROLES,
};
